version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: build templates
          command: make build-templates
          working_directory: ./test/ci
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - run:
          name: file exists
          command: cat /tmp/test
        
  
