version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: build templates
          command: make build-templates
          working_directory: ./test/ci
      - persist_to_workspace:
          root: /tmp/ci
          paths:
            - test    
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - attach_workspace:
          at: /tmp/ci
      - run:
          name: file exists
          command: cat /tmp/ci/test
                
  
workflows:
  test:
    jobs:
      - build:
          context:
            - shared
      - hold-test:
          type: approval
          requires:
            - build      
      - test:
          requires:
            - hold
          context:
            - shared