version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:      
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - checkout
      - run: docker version
      - run: docker build --help
      - run:
          name: buildx
          command: |
            export DOCKER_BUILDKIT=1
            docker build --platform=local -o . git://github.com/docker/buildx
            mkdir -p ~/.docker/cli-plugins
            mv buildx ~/.docker/cli-plugins/docker-buildx
      - run:
          name: docker build
          command: |
            export BUILDPLATFORM=linux/amd64
            export TARGETPLATFORM=linux/amd64
            BUILDPLATFORM=linux/amd64 TARGETPLATFORM=linux/amd64 make build-events-image-dev
      - run:
          name: build templates
          command: make build-templates
          working_directory: ./test/ci
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - run:
          name: file exists
          command: cat /tmp/ci/test
      - run:
          name: echo path
          command: echo $PATH
                
  
workflows:
  test:
    jobs:
      - build:
          context:
            - shared
      - hold-test:
          type: approval
          requires:
            - build      
      - test:
          requires:
            - hold-test
          context:
            - shared
