version: 2.1

parameters:
  run-tests:
    type: boolean
    default: false

jobs:
  non-test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Non-test Job
          command: echo "I am NOT testing!"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Test Job
          command: echo "I am testing!"
  all-ok:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Final Confirmation
          command: echo "All good to merge!"

workflows:
  workflow-with-test:
    when:
      or:
        - equal: [true, << pipeline.parameters.run-tests >> ]
    jobs:
      - non-test
      - test
      - all-ok:
          requires:
            - non-test
            - test
  workflow-without-test:
    when:
      or:
        - equal: [false, << pipeline.parameters.run-tests >> ]
    jobs:
      - non-test
      - all-ok:
          requires:
            - non-test
