version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-service-1-job:
    type: boolean
    default: false
  run-build-service-2-job:
    type: boolean
    default: false
  run-all-build-deploy-jobs:
    type: boolean
    default: false

jobs:
  build-service-1:
    docker:
      - image: circleci/golang:1.16
    steps:
      - echo "i am build service 1"
  build-service-2:
    docker:
      - image: circleci/golang:1.16
    steps:
      - echo "i am build service 2"

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
  # when pipeline parameter, run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  service-1:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-build-service-1-job >> ]
        - equal: [false, << pipeline.parameters.run-all-build-deploy-jobs >> ]
    jobs:
      - build-service-2:
          context:
            - shared      
  # when pipeline parameter, run-build-service-2-job is true, the
  # build-service-2 job is triggered.
  service-2:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-build-service-1-job >> ]
        - equal: [false, << pipeline.parameters.run-all-build-deploy-jobs >> ]
    jobs:
      - build-service-1:
          context:
            - shared
  all-services:
    when: << pipeline.parameters.run-all-build-deploy-jobs >>
    jobs:
      - build-service-1:
          context:
            - shared
      - build-service-2:
          context:
            - shared\